sonar.projectKey=jacksonguerrer0_umb-ci-web-inventory
sonar.organization=jackguerrero

sonar.projectName=CI Webservice Inventario
sonar.sources=src,config
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
